<?php
	$title = "Culture";
	include "./header.php";
?>
<div id="content">
	<div id="blockWithSticker" style="width:690px; padding-left:140px;">
		<img src="./images/culture/culture.png" height="76" width="142" alt="Culture in Seoul" id="aboutSeoulSticker"/>
		<p>As Korean culture spreads around the globe, more and more people come to Korea seeking to experience it first hand.</p>
		<p><span class="numberring" style="color:#D389C6;">Museums</span><br /> Seoul is home to over 100 museums, including three national and nine official municipal museums. The National Museum of Korea is the most representative of museums in not only Seoul but all of South Korea. Since its establishment in 1945, the museum has built a collection of 150,000 artifacts. In October 2005, the museum moved to a new building in Yongsan Family Park. The National Folk Museum is situated on the grounds of the Gyeongbokgung Palace in the district of Jongno-gu and uses replicas of historical objects to illustrate the folk history of the Korean people. Bukchon Hanok Village and Namsangol Hanok Village are old residential districts consisting of hanok Korean traditional houses, parks, and museums that allows visitors to experience traditional Korean culture. The War Memorial, one of nine municipal museums in Seoul, offers visitors an educational and emotional experience of various wars in which Korea was involved, including Korean War themes. The Seodaemun Prison is a former prison built during the Japanese occupation, and is currently used as a history museum. The Seoul Museum of Art and Ilmin Museum of Art have preserved the appearance of the old building that is visually unique from the neighboring tall, modern buildings. The former is operated by Seoul City Council and sits adjacent to Gyeonghuigung Palace, a Joseon dynasty royal palace. For many Korean film lovers from all over the world, the Korean Film Archive is running the Korean Film Museum and Cinematheque KOFA in its main center located in Digital Media City(DMC), Sangam-dong. The Tteok & Kitchen Utensil Museum and Kimchi Field Museum provide information regarding Korean culinary history.</p>
		<p><span class="numberring" style="color:#D389C6;">Religion</span><br /> There are also religious buildings that take important roles in Korean society and politics. The Wongudan altar was a sacrificial place where Korean rulers held heavenly rituals since the Three Kingdoms period. Since the Joseon Dynasty adopted Confucianism as its national ideology in the 14th century, the state built many Confucian shrines. The descendants of the Joseon royal family still continue to hold ceremonies to commemorate ancestors at Jongmyo. It is the oldest royal Confucian shrine preserved and the ritual ceremonies continue a tradition established in the 14th century. Munmyo and Dongmyo were built during the same period. Although Buddhism was suppressed by the Joseon state, it has continued its existence. Jogyesa is the headquarters of the Jogye Order of Korean Buddhism. Hwagyesa and Bongeunsa are also major Buddhist temples in Seoul.	The Myeongdong Cathedral is a landmark of the Myeongdong district and the biggest Catholic church established in Korea. It is a symbol of Christianity in Korea. It was also a focus for political dissent in the late-20th century. The Roman Catholic Church in South Korea has a very strong influence in Korean society, in fact the Korean Catholic Church has made a bid to host the World Youth Day but was not chosen at the moment. There are many Protestant churches in Seoul. The largest number are Presbyterian, but there are also Methodist, Baptist, and Lutheran churches.</p>
		<p><span class="numberring" style="color:#D389C6;">Festivals</span><br /> In October 2012 KBS Hall in Seoul will host major international music festivals - First ABU TV and Radio Song Festivals within frameworks of Asia-Pacific Broadcasting Union 49th General Assembly.[36][37] Hi! Seoul Festival is a seasonal cultural festival held four times a year every spring, summer, autumn, and winter in Seoul, South Korea since 2003. It is based on the "Seoul Citizens' Day" held on every October since 1994 to commemorate the 600 years history of Seoul as the capital of the country. The festival is arranged under the Seoul Metropolitan Government.</p>				
		<p><span class="numberring" style="color:#D389C6;">Parks</span><br /> Namsan Park offers hiking, recreation and views of the downtown Seoul skyline. The N Seoul Tower is located here. Seoul Olympic Park is located in Songpa-gu and was built to host the 1988 Summer Olympics. The Wongaksa Pagoda 10 tier pagoda is situated In Tapgol Park, a small public park with an area of 19,599 m2 (210,962 sq ft). Areas around streams serve as public places for relaxation and recreation. Tancheon stream and the nearby area serve as a large park with paths for both walkers and cyclists. Cheonggyecheon, a stream that runs nearly 6 km through downtown Seoul, is popular among both Seoul residents and tourists. The Seoul metropolitan area accommodates six major parks, including the Seoul Forest, which opened in mid-2005. The Seoul National Capital Area also contains a green belt aimed at preventing the city from sprawling out into neighboring Gyeonggi Province. These areas are frequently sought after by people looking to escape from urban life on weekends and during vacations.	Seoul is also home to the world's largest indoor amusement park, Lotte World. Other recreation centers include the former Olympic and World Cup stadiums and the City Hall public lawn.</p>
	</div>
	<div class="block850">
		<img src="./images/culture/culture.jpg" height="385" width="850" alt="Culture in Seoul" />
	</div>
	<div class="block850_2" style="background:#E9E9E9 url(./images/culture/pattern.jpg) repeat-x; padding:4px 0 0 0; width:850px;">
		<h1 id="culture_interview" style="padding-left:20px;">Culture interview</h1>			
		<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="850" height="330">
			<param name="movie" value="flash/culture/culture_interview.swf">
			<param name="quality" value="high">
			<embed src="flash/culture/culture_interview.swf" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="850" height="330"></embed>
		</object>
	</div>						
</div>
<?php
	include "./footer.php";
?>